[alias]
"@/*" = "./api/src/*"
"@nucleo/*" = "./api/src/nucleo/*"
"@modulos/*" = "./api/src/modulos/*"
"@api/*" = "./api/src/api/*"
"@compartido/*" = "./api/src/compartido/*"
"@tipos/*" = "./api/src/tipos/*"
"@utilidades/*" = "./api/src/utilidades/*"
"@rutas/*" = "./api/src/rutas/*"
"@componentes/*" = "./api/src/componentes/*"
"@ganchos/*" = "./api/src/ganchos/*"
"@servicios/*" = "./api/src/servicios/*"
"@infraestructura/*" = "./api/src/infraestructura/*"
"@scripts/*" = "./api/scripts/*"
"@test/*" = "./api/test/*"
"@tests/*" = "./api/tests/*"

[construccion]
objetivo = "bun"
minificar = true
division = true
mapa_fuentes = false

[memoria_cache]
directorio = "/cache_ssd/.bun"
tamano_maximo = "20GB"